name: dostrobajar
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
